apiVersion: v1
kind: Service
metadata:
  name: counter-top-service
  label :
     app : my-springbootapp
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30036
      port: 80
      targetPort: 9099
  selector:
    app: my-springbootapp
